CHINESE_FUSION_MENUS = {
    "vegan": [
        {
            "name": "Vegetable Fried Rice with Sesame Greens",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["rice", "bok choy", "carrot", "mushroom", "soy sauce"],
            "ingredient_portions": [
                {"name": "rice", "amount": 120, "unit": "g"},
                {"name": "bok choy", "amount": 40, "unit": "g"},
                {"name": "carrot", "amount": 30, "unit": "g"},
                {"name": "mushroom", "amount": 45, "unit": "g"},
                {"name": "soy sauce", "amount": 15, "unit": "ml"},
            ],
            "supplier_key": "vegetable fried rice",
        },

        {
            "name": "Mapo Tofu with Mushroom Sauce",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["tofu", "mushroom", "chili bean sauce", "spring onion"],
            "ingredient_portions": [
                {"name": "tofu", "amount": 120, "unit": "g"},
                {"name": "mushroom", "amount": 50, "unit": "g"},
                {"name": "chili bean sauce", "amount": 30, "unit": "ml"},
                {"name": "spring onion", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "tofu",
        },

        {
            "name": "Vegetable Spring Rolls",
            "category": "Side",
            "portion_amount": 120,
            "portion_unit": "g",
            "ingredients": ["cabbage", "carrot", "rice wrapper"],
            "ingredient_portions": [
                {"name": "cabbage", "amount": 50, "unit": "g"},
                {"name": "carrot", "amount": 30, "unit": "g"},
                {"name": "rice wrapper", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "spring roll",
        },

        {
            "name": "Garlic Bok Choy",
            "category": "Side",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["bok choy", "garlic", "sesame oil"],
            "ingredient_portions": [
                {"name": "bok choy", "amount": 70, "unit": "g"},
                {"name": "garlic", "amount": 10, "unit": "g"},
                {"name": "sesame oil", "amount": 10, "unit": "ml"},
            ],
            "supplier_key": "vegetable",
        },

        {
            "name": "Mango Sago Coconut Cup",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["mango", "sago", "coconut milk"],
            "ingredient_portions": [
                {"name": "mango", "amount": 40, "unit": "g"},
                {"name": "sago", "amount": 20, "unit": "g"},
                {"name": "coconut milk", "amount": 30, "unit": "ml"},
            ],
            "supplier_key": "dessert",
        },
    ],

    "vegetarian": [
        {
            "name": "Egg Fried Rice with Sesame Greens",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["rice", "egg", "bok choy", "carrot", "soy sauce"],
            "ingredient_portions": [
                {"name": "rice", "amount": 120, "unit": "g"},
                {"name": "egg", "amount": 45, "unit": "g"},
                {"name": "bok choy", "amount": 40, "unit": "g"},
                {"name": "carrot", "amount": 30, "unit": "g"},
                {"name": "soy sauce", "amount": 15, "unit": "ml"},
            ],
            "supplier_key": "fried rice",
        },
        {
            "name": "Mapo Tofu with Mushroom Sauce",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["tofu", "mushroom", "chili bean sauce", "spring onion"],
            "ingredient_portions": [
                {"name": "tofu", "amount": 120, "unit": "g"},
                {"name": "mushroom", "amount": 50, "unit": "g"},
                {"name": "chili bean sauce", "amount": 30, "unit": "ml"},
                {"name": "spring onion", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "tofu",
        },
        {
            "name": "Vegetable Spring Rolls",
            "category": "Side",
            "portion_amount": 120,
            "portion_unit": "g",
            "ingredients": ["cabbage", "carrot", "rice wrapper"],
            "ingredient_portions": [
                {"name": "cabbage", "amount": 50, "unit": "g"},
                {"name": "carrot", "amount": 30, "unit": "g"},
                {"name": "rice wrapper", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "spring roll",
        },
        {
            "name": "Garlic Bok Choy",
            "category": "Side",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["bok choy", "garlic", "sesame oil"],
            "ingredient_portions": [
                {"name": "bok choy", "amount": 70, "unit": "g"},
                {"name": "garlic", "amount": 10, "unit": "g"},
                {"name": "sesame oil", "amount": 10, "unit": "ml"},
            ],
            "supplier_key": "vegetable",
        },
        {
            "name": "Sesame Red Bean Rice Balls",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["glutinous rice", "red bean paste", "sesame"],
            "ingredient_portions": [
                {"name": "glutinous rice", "amount": 40, "unit": "g"},
                {"name": "red bean paste", "amount": 20, "unit": "g"},
                {"name": "sesame", "amount": 30, "unit": "ml"},
            ],
            "supplier_key": "dessert",
        },
    ],

    "gluten_free": [
        {
            "name": "Gluten-Free Vegetable Fried Rice",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["rice", "bok choy", "carrot", "mushroom", "gluten-free soy sauce"],
            "ingredient_portions": [
                {"name": "rice", "amount": 120, "unit": "g"},
                {"name": "bok choy", "amount": 40, "unit": "g"},
                {"name": "carrot", "amount": 30, "unit": "g"},
                {"name": "mushroom", "amount": 45, "unit": "g"},
                {"name": "gluten-free soy sauce", "amount": 15, "unit": "ml"},
            ],
            "supplier_key": "vegetable fried rice",
        },
        {
            "name": "Gluten-Free Mapo Tofu",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["tofu", "mushroom", "gluten-free chili sauce", "spring onion"],
            "ingredient_portions": [
                {"name": "tofu", "amount": 120, "unit": "g"},
                {"name": "mushroom", "amount": 50, "unit": "g"},
                {"name": "gluten-free chili sauce", "amount": 30, "unit": "ml"},
                {"name": "spring onion", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "tofu",
        },
        {
            "name": "Vegetable Spring Rolls",
            "category": "Side",
            "portion_amount": 120,
            "portion_unit": "g",
            "ingredients": ["cabbage", "carrot", "rice wrapper"],
            "ingredient_portions": [
                {"name": "cabbage", "amount": 50, "unit": "g"},
                {"name": "carrot", "amount": 30, "unit": "g"},
                {"name": "rice wrapper", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "spring roll",
        },
        {
            "name": "Garlic Bok Choy",
            "category": "Side",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["bok choy", "garlic", "sesame oil"],
            "ingredient_portions": [
                {"name": "bok choy", "amount": 70, "unit": "g"},
                {"name": "garlic", "amount": 10, "unit": "g"},
                {"name": "sesame oil", "amount": 10, "unit": "ml"},
            ],
            "supplier_key": "vegetable",
        },
        {
            "name": "Mango Coconut Sago Cup",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["mango", "sago", "coconut milk"],
            "ingredient_portions": [
                {"name": "mango", "amount": 40, "unit": "g"},
                {"name": "sago", "amount": 20, "unit": "g"},
                {"name": "coconut milk", "amount": 30, "unit": "ml"},
            ],
            "supplier_key": "dessert",
        },
    ],

    "dairy_free": [
        {
            "name": "Chicken Fried Rice",
            "category": "Main",
            "portion_amount": 260,
            "portion_unit": "g",
            "ingredients": ["chicken", "rice", "egg", "soy sauce", "spring onion"],
            "ingredient_portions": [
                {"name": "chicken", "amount": 75, "unit": "g"},
                {"name": "rice", "amount": 120, "unit": "g"},
                {"name": "egg", "amount": 45, "unit": "g"},
                {"name": "soy sauce", "amount": 15, "unit": "ml"},
                {"name": "spring onion", "amount": 5, "unit": "g"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Steamed Ginger Fish",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["fish fillet", "ginger", "soy sauce", "spring onion"],
            "ingredient_portions": [
                {"name": "fish fillet", "amount": 155, "unit": "g"},
                {"name": "ginger", "amount": 20, "unit": "g"},
                {"name": "soy sauce", "amount": 40, "unit": "ml"},
                {"name": "spring onion", "amount": 5, "unit": "g"},
            ],
            "supplier_key": "fish",
        },
        {
            "name": "Vegetable Spring Rolls",
            "category": "Side",
            "portion_amount": 120,
            "portion_unit": "g",
            "ingredients": ["cabbage", "carrot", "rice wrapper"],
            "ingredient_portions": [
                {"name": "cabbage", "amount": 50, "unit": "g"},
                {"name": "carrot", "amount": 30, "unit": "g"},
                {"name": "rice wrapper", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "spring roll",
        },
        {
            "name": "Garlic Bok Choy",
            "category": "Side",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["bok choy", "garlic", "sesame oil"],
            "ingredient_portions": [
                {"name": "bok choy", "amount": 70, "unit": "g"},
                {"name": "garlic", "amount": 10, "unit": "g"},
                {"name": "sesame oil", "amount": 10, "unit": "ml"},
            ],
            "supplier_key": "vegetable",
        },
        {
            "name": "Coconut Mango Pudding",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["mango", "coconut milk", "sugar"],
            "ingredient_portions": [
                {"name": "mango", "amount": 40, "unit": "g"},
                {"name": "coconut milk", "amount": 30, "unit": "ml"},
                {"name": "sugar", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "dessert",
        },
    ],

    "nut_allergy": [
        {
            "name": "Chicken Fried Rice",
            "category": "Main",
            "portion_amount": 260,
            "portion_unit": "g",
            "ingredients": ["chicken", "rice", "egg", "soy sauce", "spring onion"],
            "ingredient_portions": [
                {"name": "chicken", "amount": 75, "unit": "g"},
                {"name": "rice", "amount": 120, "unit": "g"},
                {"name": "egg", "amount": 45, "unit": "g"},
                {"name": "soy sauce", "amount": 15, "unit": "ml"},
                {"name": "spring onion", "amount": 5, "unit": "g"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Steamed Ginger Fish",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["fish fillet", "ginger", "soy sauce", "spring onion"],
            "ingredient_portions": [
                {"name": "fish fillet", "amount": 155, "unit": "g"},
                {"name": "ginger", "amount": 20, "unit": "g"},
                {"name": "soy sauce", "amount": 40, "unit": "ml"},
                {"name": "spring onion", "amount": 5, "unit": "g"},
            ],
            "supplier_key": "fish",
        },
        {
            "name": "Vegetable Spring Rolls",
            "category": "Side",
            "portion_amount": 120,
            "portion_unit": "g",
            "ingredients": ["cabbage", "carrot", "rice wrapper"],
            "ingredient_portions": [
                {"name": "cabbage", "amount": 50, "unit": "g"},
                {"name": "carrot", "amount": 30, "unit": "g"},
                {"name": "rice wrapper", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "spring roll",
        },
        {
            "name": "Garlic Bok Choy",
            "category": "Side",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["bok choy", "garlic", "sesame oil"],
            "ingredient_portions": [
                {"name": "bok choy", "amount": 70, "unit": "g"},
                {"name": "garlic", "amount": 10, "unit": "g"},
                {"name": "sesame oil", "amount": 10, "unit": "ml"},
            ],
            "supplier_key": "vegetable",
        },
        {
            "name": "Red Bean Sesame Balls",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["glutinous rice", "red bean paste", "sesame"],
            "ingredient_portions": [
                {"name": "glutinous rice", "amount": 40, "unit": "g"},
                {"name": "red bean paste", "amount": 20, "unit": "g"},
                {"name": "sesame", "amount": 30, "unit": "ml"},
            ],
            "supplier_key": "dessert",
        },
    ],

    "none": [
        {
            "name": "Chicken Fried Rice",
            "category": "Main",
            "portion_amount": 260,
            "portion_unit": "g",
            "ingredients": ["chicken", "rice", "egg", "soy sauce", "spring onion"],
            "ingredient_portions": [
                {"name": "chicken", "amount": 75, "unit": "g"},
                {"name": "rice", "amount": 120, "unit": "g"},
                {"name": "egg", "amount": 45, "unit": "g"},
                {"name": "soy sauce", "amount": 15, "unit": "ml"},
                {"name": "spring onion", "amount": 5, "unit": "g"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Sweet and Sour Fish",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["fish fillet", "pineapple", "capsicum", "sweet and sour sauce"],
            "ingredient_portions": [
                {"name": "fish fillet", "amount": 155, "unit": "g"},
                {"name": "pineapple", "amount": 20, "unit": "g"},
                {"name": "capsicum", "amount": 5, "unit": "ml"},
                {"name": "sweet and sour sauce", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "fish",
        },
        {
            "name": "Vegetable Spring Rolls",
            "category": "Side",
            "portion_amount": 120,
            "portion_unit": "g",
            "ingredients": ["cabbage", "carrot", "rice wrapper"],
            "ingredient_portions": [
                {"name": "cabbage", "amount": 50, "unit": "g"},
                {"name": "carrot", "amount": 30, "unit": "g"},
                {"name": "rice wrapper", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "spring roll",
        },
        {
            "name": "Garlic Bok Choy",
            "category": "Side",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["bok choy", "garlic", "sesame oil"],
            "ingredient_portions": [
                {"name": "bok choy", "amount": 70, "unit": "g"},
                {"name": "garlic", "amount": 10, "unit": "g"},
                {"name": "sesame oil", "amount": 10, "unit": "ml"},
            ],
            "supplier_key": "vegetable",
        },
        {
            "name": "Mango Coconut Sago Cup",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["mango", "sago", "coconut milk"],
            "ingredient_portions": [
                {"name": "mango", "amount": 40, "unit": "g"},
                {"name": "sago", "amount": 20, "unit": "g"},
                {"name": "coconut milk", "amount": 30, "unit": "ml"},
            ],
            "supplier_key": "dessert",
        },
    ],
}