JAPANESE_FUSION_MENUS = {
    "vegan": [
        {
            "name": "Vegetable Sushi Platter",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["sushi rice", "avocado", "cucumber", "carrot", "tamari"],
            "ingredient_portions": [
                {"name": "sushi rice", "amount": 90, "unit": "g"},
                {"name": "avocado", "amount": 35, "unit": "g"},
                {"name": "cucumber", "amount": 25, "unit": "g"},
                {"name": "carrot", "amount": 25, "unit": "g"},
                {"name": "tamari", "amount": 5, "unit": "ml"},
            ],
            "supplier_key": "vegetable sushi platter",
        },
        {
            "name": "Mushroom Teriyaki Bowl",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["mushroom", "rice", "vegan teriyaki sauce", "seasonal vegetables"],
            "ingredient_portions": [
                {"name": "mushroom", "amount": 90, "unit": "g"},
                {"name": "rice", "amount": 110, "unit": "g"},
                {"name": "vegan teriyaki sauce", "amount": 20, "unit": "ml"},
                {"name": "seasonal vegetables", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "mushroom",
        },

        {
            "name": "Agedashi Tofu with Ginger Vegetable Broth",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["tofu", "rice flour", "ginger vegetable broth", "nori"],
            "ingredient_portions": [
                {"name": "tofu", "amount": 100, "unit": "g"},
                {"name": "rice flour", "amount": 20, "unit": "g"},
                {"name": "ginger vegetable broth", "amount": 50, "unit": "ml"},
                {"name": "nori", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "tofu",
        },

        {
            "name": "Edamame Side Dish",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["edamame", "sea salt"],
            "ingredient_portions": [
                {"name": "edamame", "amount": 75, "unit": "g"},
                {"name": "sea salt", "amount": 5, "unit": "g"},
            ],
            "supplier_key": "edamame",
        },

        {
            "name": "Matcha Red Bean Mochi",
            "category": "Dessert",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["matcha", "vegan mochi", "red bean paste"],
            "ingredient_portions": [
                {"name": "matcha", "amount": 10, "unit": "g"},
                {"name": "vegan mochi", "amount": 45, "unit": "g"},
                {"name": "red bean paste", "amount": 25, "unit": "g"},
            ],
            "supplier_key": "matcha mochi dessert",
        },
    ],
    
    "vegetarian": [
        {
            "name": "Vegetable Sushi Platter",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["sushi rice", "avocado", "cucumber", "carrot", "tamari"],
            "ingredient_portions": [
                {"name": "sushi rice", "amount": 90, "unit": "g"},
                {"name": "avocado", "amount": 35, "unit": "g"},
                {"name": "cucumber", "amount": 25, "unit": "g"},
                {"name": "carrot", "amount": 25, "unit": "g"},
                {"name": "tamari", "amount": 5, "unit": "ml"},
            ],
            "supplier_key": "vegetable sushi platter",
        },
        {
            "name": "Mushroom Teriyaki Bowl",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["mushroom", "rice", "vegan teriyaki sauce", "seasonal vegetables"],
            "ingredient_portions": [
                {"name": "mushroom", "amount": 90, "unit": "g"},
                {"name": "rice", "amount": 110, "unit": "g"},
                {"name": "vegan teriyaki sauce", "amount": 20, "unit": "ml"},
                {"name": "seasonal vegetables", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "mushroom",
        },

        {
            "name": "Agedashi Tofu with Ginger Vegetable Broth",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["tofu", "rice flour", "ginger vegetable broth", "nori"],
            "ingredient_portions": [
                {"name": "tofu", "amount": 100, "unit": "g"},
                {"name": "rice flour", "amount": 20, "unit": "g"},
                {"name": "ginger vegetable broth", "amount": 50, "unit": "ml"},
                {"name": "nori", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "tofu",
        },

        {
            "name": "Edamame Side Dish",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["edamame", "sea salt"],
            "ingredient_portions": [
                {"name": "edamame", "amount": 75, "unit": "g"},
                {"name": "sea salt", "amount": 5, "unit": "g"},
            ],
            "supplier_key": "edamame",
        },

        {
            "name": "Matcha Red Bean Mochi",
            "category": "Dessert",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["matcha", "vegan mochi", "red bean paste"],
            "ingredient_portions": [
                {"name": "matcha", "amount": 10, "unit": "g"},
                {"name": "vegan mochi", "amount": 45, "unit": "g"},
                {"name": "red bean paste", "amount": 25, "unit": "g"},
            ],
            "supplier_key": "matcha mochi dessert",
        },
    ],

    "gluten_free": [
        {
            "name": "Gluten-Free Vegetable Sushi Platter",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["sushi rice", "avocado", "cucumber", "carrot", "gluten-free tamari"],
            "ingredient_portions": [
                {"name": "sushi rice", "amount": 90, "unit": "g"},
                {"name": "avocado", "amount": 35, "unit": "g"},
                {"name": "cucumber", "amount": 25, "unit": "g"},
                {"name": "carrot", "amount": 25, "unit": "g"},
                {"name": "gluten-free tamari", "amount": 5, "unit": "ml"},
            ],
            "supplier_key": "vegetable sushi platter",
        },
        {
            "name": "Gluten-Free Mushroom Teriyaki Bowl",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["mushroom", "rice", "gluten-free teriyaki sauce", "seasonal vegetables"],
            "ingredient_portions": [
                {"name": "mushroom", "amount": 90, "unit": "g"},
                {"name": "rice", "amount": 110, "unit": "g"},
                {"name": "gluten-free teriyaki sauce", "amount": 20, "unit": "ml"},
                {"name": "seasonal vegetables", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "mushroom",
        },
        {
            "name": "Rice-Flour Agedashi Tofu",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["tofu", "rice flour", "ginger vegetable broth", "nori"],
            "ingredient_portions": [
                {"name": "tofu", "amount": 100, "unit": "g"},
                {"name": "rice flour", "amount": 20, "unit": "g"},
                {"name": "ginger vegetable broth", "amount": 50, "unit": "ml"},
                {"name": "nori", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "tofu",
        },
        {
            "name": "Edamame Side Dish",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["edamame", "sea salt"],
            "ingredient_portions": [
                {"name": "edamame", "amount": 75, "unit": "g"},
                {"name": "sea salt", "amount": 5, "unit": "g"},
            ],
            "supplier_key": "edamame",
        },
        {
            "name": "Matcha Red Bean Mochi",
            "category": "Dessert",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["matcha", "gluten-free mochi", "red bean paste"],
            "ingredient_portions": [
                {"name": "matcha", "amount": 10, "unit": "g"},
                {"name": "gluten-free mochi", "amount": 55, "unit": "g"},
                {"name": "red bean paste", "amount": 25, "unit": "g"},
            ],
            "supplier_key": "matcha mochi dessert",
        },
    ],

    "dairy_free": [
        {
            "name": "Vegetable Sushi Platter",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["sushi rice", "avocado", "cucumber", "carrot", "tamari"],
            "ingredient_portions": [
                {"name": "sushi rice", "amount": 90, "unit": "g"},
                {"name": "avocado", "amount": 35, "unit": "g"},
                {"name": "cucumber", "amount": 25, "unit": "g"},
                {"name": "carrot", "amount": 25, "unit": "g"},
                {"name": "tamari", "amount": 5, "unit": "ml"},
            ],
            "supplier_key": "vegetable sushi platter",
        },
        {
            "name": "Mushroom Teriyaki Bowl",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["mushroom", "rice", "teriyaki sauce", "seasonal vegetables"],
            "ingredient_portions": [
                {"name": "mushroom", "amount": 90, "unit": "g"},
                {"name": "rice", "amount": 110, "unit": "g"},
                {"name": "teriyaki sauce", "amount": 20, "unit": "ml"},
                {"name": "seasonal vegetables", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "mushroom",
        },
        {
            "name": "Agedashi Tofu with Ginger Vegetable Broth",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["tofu", "rice flour", "ginger vegetable broth", "nori"],
            "ingredient_portions": [
                {"name": "tofu", "amount": 100, "unit": "g"},
                {"name": "rice flour", "amount": 20, "unit": "g"},
                {"name": "ginger vegetable broth", "amount": 50, "unit": "ml"},
                {"name": "nori", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "tofu",
        },
        {
            "name": "Edamame Side Dish",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["edamame", "sea salt"],
            "ingredient_portions": [
                {"name": "edamame", "amount": 75, "unit": "g"},
                {"name": "sea salt", "amount": 5, "unit": "g"},
            ],
            "supplier_key": "edamame",
        },
        {
            "name": "Coconut Matcha Pudding Cup",
            "category": "Dessert",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["matcha", "coconut milk", "sugar"],
            "ingredient_portions": [
                {"name": "matcha", "amount": 10, "unit": "g"},
                {"name": "coconut milk", "amount": 45, "unit": "g"},
                {"name": "sugar", "amount": 25, "unit": "g"},
            ],
            "supplier_key": "dessert",
        },
    ],

    "nut_allergy": [
        {
            "name": "Vegetable Sushi Platter",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["sushi rice", "avocado", "cucumber", "carrot", "tamari"],
            "ingredient_portions": [
                {"name": "sushi rice", "amount": 90, "unit": "g"},
                {"name": "avocado", "amount": 35, "unit": "g"},
                {"name": "cucumber", "amount": 25, "unit": "g"},
                {"name": "carrot", "amount": 25, "unit": "g"},
                {"name": "tamari", "amount": 5, "unit": "ml"},
            ],
            "supplier_key": "vegetable sushi platter",
        },
        {
            "name": "Mushroom Teriyaki Bowl",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["mushroom", "rice", "teriyaki sauce", "seasonal vegetables"],
            "ingredient_portions": [
                {"name": "mushroom", "amount": 90, "unit": "g"},
                {"name": "rice", "amount": 110, "unit": "g"},
                {"name": "teriyaki sauce", "amount": 20, "unit": "ml"},
                {"name": "seasonal vegetables", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "mushroom",
        },
        {
            "name": "Agedashi Tofu with Ginger Vegetable Broth",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["tofu", "rice flour", "ginger vegetable broth", "nori"],
            "ingredient_portions": [
                {"name": "tofu", "amount": 100, "unit": "g"},
                {"name": "rice flour", "amount": 20, "unit": "g"},
                {"name": "ginger vegetable broth", "amount": 50, "unit": "ml"},
                {"name": "nori", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "tofu",
        },
        {
            "name": "Edamame Side Dish",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["edamame", "sea salt"],
            "ingredient_portions": [
                {"name": "edamame", "amount": 75, "unit": "g"},
                {"name": "sea salt", "amount": 5, "unit": "g"},
            ],
            "supplier_key": "edamame",
        },
        {
            "name": "Matcha Red Bean Mochi",
            "category": "Dessert",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["matcha", "mochi", "red bean paste"],
            "ingredient_portions": [
                {"name": "matcha", "amount": 10, "unit": "g"},
                {"name": "gluten-free mochi", "amount": 55, "unit": "g"},
                {"name": "red bean paste", "amount": 25, "unit": "g"},
            ],
            "supplier_key": "matcha mochi dessert",
        },
    ],

    "none": [
        {
            "name": "Teriyaki Chicken Donburi",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["chicken", "rice", "teriyaki sauce", "seasonal vegetables"],
            "ingredient_portions": [
                {"name": "chicken", "amount": 90, "unit": "g"},
                {"name": "rice", "amount": 110, "unit": "g"},
                {"name": "teriyaki sauce", "amount": 20, "unit": "g"},
                {"name": "seasonal vegetables", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Salmon Sushi Platter",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["sushi rice", "salmon", "cucumber", "nori", "tamari"],
            "ingredient_portions": [
                {"name": "sushi rice", "amount": 90, "unit": "g"},
                {"name": "salmon", "amount": 50, "unit": "g"},
                {"name": "cucumber", "amount": 25, "unit": "g"},
                {"name": "nori", "amount": 30, "unit": "g"},
                {"name": "tamari", "amount": 5, "unit": "ml"},
            ],
            "supplier_key": "fish",
        },
        {
            "name": "Agedashi Tofu with Ginger Broth",
            "category": "Main",
            "portion_amount": 180,
            "portion_unit": "g",
            "ingredients": ["tofu", "rice flour", "ginger broth", "nori"],
            "ingredient_portions": [
                {"name": "tofu", "amount": 100, "unit": "g"},
                {"name": "rice flour", "amount": 20, "unit": "g"},
                {"name": "ginger broth", "amount": 50, "unit": "ml"},
                {"name": "nori", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "tofu",
        },
        {
            "name": "Edamame Side Dish",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["edamame", "sea salt"],
            "ingredient_portions": [
                {"name": "edamame", "amount": 75, "unit": "g"},
                {"name": "sea salt", "amount": 5, "unit": "g"},
            ],
            "supplier_key": "edamame",
        },
        {
            "name": "Matcha Mochi Dessert",
            "category": "Dessert",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["matcha", "mochi", "red bean paste"],
            "ingredient_portions": [
                {"name": "matcha", "amount": 10, "unit": "g"},
                {"name": "mochi", "amount": 55, "unit": "g"},
                {"name": "red bean paste", "amount": 25, "unit": "g"},
            ],
            "supplier_key": "matcha mochi dessert",
        },
    ],
}