TRADITIONAL_MALAY_MENUS = {
    "vegan": [
        {
            "name": "Nasi Lemak with Sambal Mushroom",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["coconut rice", "mushroom sambal", "cucumber", "fried tempeh"],
            "ingredient_portions": [
                {"name": "coconut rice", "amount": 140, "unit": "g"},
                {"name": "mushroom sambal", "amount": 50, "unit": "g"},
                {"name": "cucumber", "amount": 20, "unit": "g"},
                {"name": "fried tempeh", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "mushroom",
        },

        {
            "name": "Sayur Lodeh Kampung",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["cabbage", "carrot", "long beans", "coconut milk"],
            "ingredient_portions": [
                {"name": "cabbage", "amount": 70, "unit": "g"},
                {"name": "carrot", "amount": 40, "unit": "g"},
                {"name": "long beans", "amount": 50, "unit": "g"},
                {"name": "coconut milk", "amount": 60, "unit": "ml"},
            ],
            "supplier_key": "vegetable curry",
        },

        {
            "name": "Vegetable Curry Puff",
            "category": "Side",
            "portion_amount": 100,
            "portion_unit": "g",
            "ingredients": ["potato", "carrot", "curry spices", "pastry"],
            "ingredient_portions": [
                {"name": "potato", "amount": 45, "unit": "g"},
                {"name": "carrot", "amount": 20, "unit": "g"},
                {"name": "curry spices", "amount": 10, "unit": "g"},
                {"name": "pastry", "amount": 25, "unit": "g"},
            ],
            "supplier_key": "curry puff",
        },

        {
            "name": "Acar Timun",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["cucumber", "carrot", "vinegar", "sugar"],
            "ingredient_portions": [
                {"name": "cucumber", "amount": 35, "unit": "g"},
                {"name": "carrot", "amount": 20, "unit": "g"},
                {"name": "vinegar", "amount": 15, "unit": "ml"},
                {"name": "sugar", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "pickled vegetables",
        },

        {
            "name": "Kuih Seri Muka",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["glutinous rice", "pandan", "coconut milk"],
            "ingredient_portions": [
                {"name": "glutinous rice", "amount": 40, "unit": "g"},
                {"name": "pandan", "amount": 15, "unit": "g"},
                {"name": "coconut milk", "amount": 35, "unit": "ml"},
            ],
            "supplier_key": "traditional kuih",
        },
    ],

    "vegetarian": [
        {
            "name": "Nasi Lemak with Egg and Sambal",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["coconut rice", "egg", "sambal", "cucumber"],
            "ingredient_portions": [
                {"name": "coconut rice", "amount": 140, "unit": "g"},
                {"name": "egg", "amount": 50, "unit": "g"},
                {"name": "sambal", "amount": 40, "unit": "g"},
                {"name": "cucumber", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "nasi lemak",
        },
        {
            "name": "Sayur Lodeh Kampung",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["cabbage", "carrot", "long beans", "coconut milk"],
            "ingredient_portions": [
                {"name": "cabbage", "amount": 70, "unit": "g"},
                {"name": "carrot", "amount": 40, "unit": "g"},
                {"name": "long beans", "amount": 50, "unit": "g"},
                {"name": "coconut milk", "amount": 60, "unit": "ml"},
            ],
            "supplier_key": "vegetable curry",
        },
        {
            "name": "Vegetable Curry Puff",
            "category": "Side",
            "portion_amount": 100,
            "portion_unit": "g",
            "ingredients": ["potato", "carrot", "curry spices", "pastry"],
            "ingredient_portions": [
                {"name": "potato", "amount": 45, "unit": "g"},
                {"name": "carrot", "amount": 20, "unit": "g"},
                {"name": "curry spices", "amount": 10, "unit": "g"},
                {"name": "pastry", "amount": 25, "unit": "g"},
            ],
            "supplier_key": "curry puff",
        },
        {
            "name": "Acar Timun",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["cucumber", "carrot", "vinegar", "sugar"],
            "ingredient_portions": [
                {"name": "cucumber", "amount": 35, "unit": "g"},
                {"name": "carrot", "amount": 20, "unit": "g"},
                {"name": "vinegar", "amount": 15, "unit": "ml"},
                {"name": "sugar", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "pickled vegetables",
        },
        {
            "name": "Kuih Lapis Pandan",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["rice flour", "pandan", "coconut milk"],
            "ingredient_portions": [
                {"name": "rice flour", "amount": 40, "unit": "g"},
                {"name": "pandan", "amount": 15, "unit": "g"},
                {"name": "coconut milk", "amount": 35, "unit": "ml"},
            ],
            "supplier_key": "traditional kuih",
        },
    ],

    "gluten_free": [
        {
            "name": "Gluten-Free Nasi Lemak Chicken",
            "category": "Main",
            "portion_amount": 260,
            "portion_unit": "g",
            "ingredients": ["coconut rice", "chicken sambal", "cucumber", "egg"],
            "ingredient_portions": [
                {"name": "coconut rice", "amount": 140, "unit": "g"},
                {"name": "chicken sambal", "amount": 50, "unit": "g"},
                {"name": "cucumber", "amount": 20, "unit": "g"},
                {"name": "egg", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Grilled Turmeric Fish",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["fish", "turmeric", "lime", "chili"],
            "ingredient_portions": [
                {"name": "fish", "amount": 160, "unit": "g"},
                {"name": "turmeric", "amount": 20, "unit": "g"},
                {"name": "lime", "amount": 20, "unit": "ml"},
                {"name": "chili", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "fish",
        },
        {
            "name": "Steamed Cassava Cake",
            "category": "Side",
            "portion_amount": 100,
            "portion_unit": "g",
            "ingredients": ["cassava", "coconut milk", "sugar"],
            "ingredient_portions": [
                {"name": "cassava", "amount": 70, "unit": "g"},
                {"name": "coconut milk", "amount": 60, "unit": "ml"},
                {"name": "sugar", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "traditional snack",
        },
        {
            "name": "Acar Timun",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["cucumber", "carrot", "vinegar", "sugar"],
            "ingredient_portions": [
                {"name": "cucumber", "amount": 35, "unit": "g"},
                {"name": "carrot", "amount": 20, "unit": "g"},
                {"name": "vinegar", "amount": 15, "unit": "ml"},
                {"name": "sugar", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "pickled vegetables",
        },
        {
            "name": "Kuih Seri Muka",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["glutinous rice", "pandan", "coconut milk"],
            "ingredient_portions": [
                {"name": "glutinous rice", "amount": 40, "unit": "g"},
                {"name": "pandan", "amount": 15, "unit": "g"},
                {"name": "coconut milk", "amount": 35, "unit": "ml"},
            ],
            "supplier_key": "traditional kuih",
        },
    ],

    "dairy_free": [
        {
            "name": "Ayam Rendang with Coconut Rice",
            "category": "Main",
            "portion_amount": 260,
            "portion_unit": "g",
            "ingredients": ["chicken", "coconut milk", "rendang spices", "rice"],
            "ingredient_portions": [
                {"name": "chicken", "amount": 60, "unit": "g"},
                {"name": "coconut milk", "amount": 50, "unit": "ml"},
                {"name": "rendang spices", "amount": 20, "unit": "g"},
                {"name": "rice", "amount": 130, "unit": "g"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Ikan Bakar Sambal",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["fish", "sambal", "lime", "banana leaf"],
            "ingredient_portions": [
                {"name": "fish", "amount": 160, "unit": "g"},
                {"name": "sambal", "amount": 20, "unit": "g"},
                {"name": "lime", "amount": 20, "unit": "ml"},
                {"name": "banana leaf", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "fish",
        },
        {
            "name": "Vegetable Curry Puff",
            "category": "Side",
            "portion_amount": 100,
            "portion_unit": "g",
            "ingredients": ["potato", "carrot", "curry spices", "pastry"],
            "ingredient_portions": [
                {"name": "potato", "amount": 45, "unit": "g"},
                {"name": "carrot", "amount": 20, "unit": "g"},
                {"name": "curry spices", "amount": 10, "unit": "g"},
                {"name": "pastry", "amount": 25, "unit": "g"},
            ],
            "supplier_key": "curry puff",
        },
        {
            "name": "Acar Timun",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["cucumber", "carrot", "vinegar", "sugar"],
            "ingredient_portions": [
                {"name": "cucumber", "amount": 35, "unit": "g"},
                {"name": "carrot", "amount": 20, "unit": "g"},
                {"name": "vinegar", "amount": 15, "unit": "ml"},
                {"name": "sugar", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "pickled vegetables",
        },
        {
            "name": "Kuih Ketayap",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["pandan crepe", "grated coconut", "palm sugar"],
            "ingredient_portions": [
                {"name": "pandan crepe", "amount": 40, "unit": "g"},
                {"name": "grated coconutan", "amount": 15, "unit": "g"},
                {"name": "palm sugar", "amount": 35, "unit": "ml"},
            ],
            "supplier_key": "traditional kuih",
        },
    ],

    "nut_allergy": [
        {
            "name": "Ayam Rendang with Coconut Rice",
            "category": "Main",
            "portion_amount": 260,
            "portion_unit": "g",
            "ingredients": ["chicken", "coconut milk", "rendang spices", "rice"],
            "ingredient_portions": [
                {"name": "chicken", "amount": 60, "unit": "g"},
                {"name": "coconut milk", "amount": 50, "unit": "ml"},
                {"name": "rendang spices", "amount": 20, "unit": "g"},
                {"name": "rice", "amount": 130, "unit": "g"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Ikan Bakar Sambal",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["fish", "sambal", "lime", "banana leaf"],
            "ingredient_portions": [
                {"name": "fish", "amount": 160, "unit": "g"},
                {"name": "sambal", "amount": 20, "unit": "g"},
                {"name": "lime", "amount": 20, "unit": "ml"},
                {"name": "banana leaf", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "fish",
        },
        {
            "name": "Vegetable Curry Puff",
            "category": "Side",
            "portion_amount": 100,
            "portion_unit": "g",
            "ingredients": ["potato", "carrot", "curry spices", "pastry"],
            "ingredient_portions": [
                {"name": "potato", "amount": 45, "unit": "g"},
                {"name": "carrot", "amount": 20, "unit": "g"},
                {"name": "curry spices", "amount": 10, "unit": "g"},
                {"name": "pastry", "amount": 25, "unit": "g"},
            ],
            "supplier_key": "curry puff",
        },
        {
            "name": "Acar Timun",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["cucumber", "carrot", "vinegar", "sugar"],
            "ingredient_portions": [
                {"name": "cucumber", "amount": 35, "unit": "g"},
                {"name": "carrot", "amount": 20, "unit": "g"},
                {"name": "vinegar", "amount": 15, "unit": "ml"},
                {"name": "sugar", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "pickled vegetables",
        },
        {
            "name": "Kuih Lapis Pandan",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["rice flour", "pandan", "coconut milk"],
            "ingredient_portions": [
                {"name": "rice flour", "amount": 40, "unit": "g"},
                {"name": "pandan", "amount": 15, "unit": "g"},
                {"name": "coconut milk", "amount": 35, "unit": "ml"},
            ],
            "supplier_key": "traditional kuih",
        },
    ],

    "none": [
        {
            "name": "Ayam Rendang with Coconut Rice",
            "category": "Main",
            "portion_amount": 260,
            "portion_unit": "g",
            "ingredients": ["chicken", "coconut milk", "rendang spices", "rice"],
            "ingredient_portions": [
                {"name": "chicken", "amount": 60, "unit": "g"},
                {"name": "coconut milk", "amount": 50, "unit": "ml"},
                {"name": "rendang spices", "amount": 20, "unit": "g"},
                {"name": "rice", "amount": 130, "unit": "g"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Ikan Bakar Sambal",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["fish", "sambal", "lime", "banana leaf"],
            "ingredient_portions": [
                {"name": "fish", "amount": 160, "unit": "g"},
                {"name": "sambal", "amount": 20, "unit": "g"},
                {"name": "lime", "amount": 20, "unit": "ml"},
                {"name": "banana leaf", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "fish",
        },
        {
            "name": "Beef Satay with Peanut-Free Sauce",
            "category": "Main",
            "portion_amount": 200,
            "portion_unit": "g",
            "ingredients": ["beef", "satay spices", "soy sauce"],
            "ingredient_portions": [
                {"name": "beef", "amount": 160, "unit": "g"},
                {"name": "satay spices", "amount": 20, "unit": "g"},
                {"name": "soy sauce", "amount": 20, "unit": "ml"},
            ],
            "supplier_key": "beef",
        },
        {
            "name": "Acar Timun",
            "category": "Side",
            "portion_amount": 80,
            "portion_unit": "g",
            "ingredients": ["cucumber", "carrot", "vinegar", "sugar"],
            "ingredient_portions": [
                {"name": "cucumber", "amount": 35, "unit": "g"},
                {"name": "carrot", "amount": 20, "unit": "g"},
                {"name": "vinegar", "amount": 15, "unit": "ml"},
                {"name": "sugar", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "pickled vegetables",
        },
        {
            "name": "Kuih Seri Muka",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["glutinous rice", "pandan", "coconut milk"],
            "ingredient_portions": [
                {"name": "glutinous rice", "amount": 40, "unit": "g"},
                {"name": "pandan", "amount": 15, "unit": "g"},
                {"name": "coconut milk", "amount": 35, "unit": "ml"},
            ],
            "supplier_key": "traditional kuih",
        },
    ],
}