WESTERN_CORPORATE_MENUS = {
    "vegan": [
        {
            "name": "Grilled Vegetable Pasta",
            "category": "Main",
            "portion_amount": 260,
            "portion_unit": "g",
            "ingredients": ["penne pasta", "zucchini", "capsicum", "olive oil"],
            "ingredient_portions": [
                {"name": "penne pasta", "amount": 120, "unit": "g"},
                {"name": "zucchini", "amount": 60, "unit": "g"},
                {"name": "capsicum", "amount": 60, "unit": "g"},
                {"name": "olive oil", "amount": 20, "unit": "ml"},
            ],
            "supplier_key": "vegetable pasta",
        },

        {
            "name": "Herb Roasted Vegetable Bowl",
            "category": "Main",
            "portion_amount": 240,
            "portion_unit": "g",
            "ingredients": ["pumpkin", "broccoli", "quinoa", "olive oil", "mixed herbs"],
            "ingredient_portions": [
                {"name": "pumpkin", "amount": 70, "unit": "g"},
                {"name": "broccoli", "amount": 60, "unit": "g"},
                {"name": "quinoa", "amount": 70, "unit": "g"},
                {"name": "olive oil", "amount": 20, "unit": "ml"},
                {"name": "mixed herbs", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "vegetable bowl",
        },

        {
            "name": "Tomato Bruschetta",
            "category": "Side",
            "portion_amount": 100,
            "portion_unit": "g",
            "ingredients": ["tomato", "basil", "olive oil", "bread"],
            "ingredient_portions": [
                {"name": "tomato", "amount": 40, "unit": "g"},
                {"name": "basil", "amount": 10, "unit": "g"},
                {"name": "olive oil", "amount": 10, "unit": "ml"},
                {"name": "bread", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "bruschetta",
        },

        {
            "name": "Garden Salad Cup",
            "category": "Side",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["lettuce", "cucumber", "cherry tomato", "vinaigrette"],
            "ingredient_portions": [
                {"name": "lettuce", "amount": 35, "unit": "g"},
                {"name": "cucumber", "amount": 20, "unit": "g"},
                {"name": "cherry tomato", "amount": 20, "unit": "g"},
                {"name": "vinaigrette", "amount": 15, "unit": "ml"},
            ],
            "supplier_key": "salad",
        },

        {
            "name": "Berry Chia Coconut Pudding",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["chia seeds", "coconut milk", "mixed berries"],
            "ingredient_portions": [
                {"name": "chia seeds", "amount": 20, "unit": "g"},
                {"name": "coconut milk", "amount": 40, "unit": "ml"},
                {"name": "mixed berries", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "dessert",
        },
    ],

    "vegetarian": [
        {
            "name": "Creamy Mushroom Pasta",
            "category": "Main",
            "portion_amount": 260,
            "portion_unit": "g",
            "ingredients": ["penne pasta", "mushroom", "cream sauce", "parmesan"],
            "ingredient_portions": [
                {"name": "penne pasta", "amount": 120, "unit": "g"},
                {"name": "mushroom", "amount": 50, "unit": "g"},
                {"name": "cream sauce", "amount": 40, "unit": "ml"},
                {"name": "parmesan", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "mushroom pasta",
        },
        {
            "name": "Spinach and Cheese Quiche",
            "category": "Main",
            "portion_amount": 220,
            "portion_unit": "g",
            "ingredients": ["spinach", "egg", "cheese", "pastry crust"],
            "ingredient_portions": [
                {"name": "spinach", "amount": 100, "unit": "g"},
                {"name": "egg", "amount": 80, "unit": "g"},
                {"name": "cheese", "amount": 50, "unit": "g"},
                {"name": "pastry crust", "amount": 90, "unit": "g"},
            ],
            "supplier_key": "vegetarian quiche",
        },
        {
            "name": "Tomato Bruschetta",
            "category": "Side",
            "portion_amount": 100,
            "portion_unit": "g",
            "ingredients": ["tomato", "basil", "olive oil", "bread"],
            "ingredient_portions": [
                {"name": "tomato", "amount": 40, "unit": "g"},
                {"name": "basil", "amount": 10, "unit": "g"},
                {"name": "olive oil", "amount": 10, "unit": "ml"},
                {"name": "bread", "amount": 40, "unit": "g"},
            ],
            "supplier_key": "bruschetta",
        },
        {
            "name": "Garden Salad Cup",
            "category": "Side",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["lettuce", "cucumber", "cherry tomato", "vinaigrette"],
            "ingredient_portions": [
                {"name": "lettuce", "amount": 35, "unit": "g"},
                {"name": "cucumber", "amount": 20, "unit": "g"},
                {"name": "cherry tomato", "amount": 20, "unit": "g"},
                {"name": "vinaigrette", "amount": 15, "unit": "ml"},
            ],
            "supplier_key": "salad",
        },
        {
            "name": "Mini Cheesecake Cup",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["cream cheese", "biscuit base", "berry topping"],
            "ingredient_portions": [
                {"name": "cream cheese", "amount": 20, "unit": "g"},
                {"name": "biscuit base", "amount": 40, "unit": "g"},
                {"name": "berry topping", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "dessert",
        },
    ],

    "gluten_free": [
        {
            "name": "Gluten-Free Herb Chicken Bowl",
            "category": "Main",
            "portion_amount": 270,
            "portion_unit": "g",
            "ingredients": ["chicken breast", "quinoa", "broccoli", "olive oil"],
            "ingredient_portions": [
                {"name": "chicken breast", "amount": 100, "unit": "g"},
                {"name": "quinoa", "amount": 90, "unit": "g"},
                {"name": "broccoli", "amount": 60, "unit": "g"},
                {"name": "olive oil", "amount": 20, "unit": "ml"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Grilled Salmon with Vegetables",
            "category": "Main",
            "portion_amount": 240,
            "portion_unit": "g",
            "ingredients": ["salmon", "asparagus", "carrot", "herb seasoning"],
            "ingredient_portions": [
                {"name": "salmon", "amount": 120, "unit": "g"},
                {"name": "asparagus", "amount": 60, "unit": "g"},
                {"name": "carrot", "amount": 40, "unit": "g"},
                {"name": "herb seasoning", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "fish",
        },
        {
            "name": "Gluten-Free Caesar Salad",
            "category": "Side",
            "portion_amount": 100,
            "portion_unit": "g",
            "ingredients": ["lettuce", "parmesan", "gluten-free croutons", "caesar dressing"],
            "ingredient_portions": [
                {"name": "lettuce", "amount": 35, "unit": "g"},
                {"name": "parmesan", "amount": 20, "unit": "g"},
                {"name": "gluten-free croutons", "amount": 30, "unit": "g"},
                {"name": "caesar dressing", "amount": 15, "unit": "ml"},
            ],
            "supplier_key": "salad",
        },
        {
            "name": "Fruit Salad Cup",
            "category": "Side",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["melon", "grapes", "strawberries"],
            "ingredient_portions": [
                {"name": "melon", "amount": 40, "unit": "g"},
                {"name": "grapes", "amount": 25, "unit": "g"},
                {"name": "strawberries", "amount": 25, "unit": "g"},
            ],
            "supplier_key": "fruit cup",
        },
        {
            "name": "Chocolate Mousse Cup",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["dark chocolate", "cream", "cocoa powder"],
            "ingredient_portions": [
                {"name": "dark chocolate", "amount": 20, "unit": "g"},
                {"name": "cream", "amount": 40, "unit": "ml"},
                {"name": "cocoa powder", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "dessert",
        },
    ],

    "dairy_free": [
        {
            "name": "Herb Grilled Chicken with Rice",
            "category": "Main",
            "portion_amount": 270,
            "portion_unit": "g",
            "ingredients": ["chicken breast", "rice", "olive oil", "mixed herbs"],
            "ingredient_portions": [
                {"name": "chicken breast", "amount": 100, "unit": "g"},
                {"name": "rice", "amount": 90, "unit": "g"},
                {"name": "olive oil", "amount": 20, "unit": "ml"},
                {"name": "mixed herbs", "amount": 60, "unit": "g"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Lemon Garlic Fish Fillet",
            "category": "Main",
            "portion_amount": 240,
            "portion_unit": "g",
            "ingredients": ["fish fillet", "garlic", "lemon", "olive oil"],
            "ingredient_portions": [
                {"name": "fish fillet", "amount": 120, "unit": "g"},
                {"name": "garlic", "amount": 60, "unit": "g"},
                {"name": "lemon", "amount": 40, "unit": "g"},
                {"name": "olive oil", "amount": 20, "unit": "ml"},
            ],
            "supplier_key": "fish",
        },
        {
            "name": "Garden Salad Cup",
            "category": "Side",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["lettuce", "cucumber", "cherry tomato", "vinaigrette"],
            "ingredient_portions": [
                {"name": "lettuce", "amount": 35, "unit": "g"},
                {"name": "cucumber", "amount": 20, "unit": "g"},
                {"name": "cherry tomato", "amount": 20, "unit": "g"},
                {"name": "vinaigrette", "amount": 15, "unit": "ml"},
            ],
            "supplier_key": "salad",
        },
        {
            "name": "Roasted Potato Wedges",
            "category": "Side",
            "portion_amount": 120,
            "portion_unit": "g",
            "ingredients": ["potato", "olive oil", "paprika"],
            "ingredient_portions": [
                {"name": "potato", "amount": 80, "unit": "g"},
                {"name": "olive oil", "amount": 10, "unit": "ml"},
                {"name": "paprika", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "potato wedges",
        },
        {
            "name": "Coconut Berry Pudding",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["coconut milk", "berries", "chia seeds"],
            "ingredient_portions": [
                {"name": "coconut milk", "amount": 40, "unit": "ml"},
                {"name": "mixed berries", "amount": 30, "unit": "g"},
                {"name": "chia seeds", "amount": 20, "unit": "g"},
            ],
            "supplier_key": "dessert",
        },
    ],

    "nut_allergy": [
        {
            "name": "Herb Grilled Chicken with Rice",
            "category": "Main",
            "portion_amount": 270,
            "portion_unit": "g",
            "ingredients": ["chicken breast", "rice", "olive oil", "mixed herbs"],
            "ingredient_portions": [
                {"name": "chicken breast", "amount": 100, "unit": "g"},
                {"name": "rice", "amount": 90, "unit": "g"},
                {"name": "olive oil", "amount": 20, "unit": "ml"},
                {"name": "mixed herbs", "amount": 60, "unit": "g"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Beef Steak with Pepper Sauce",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["beef steak", "black pepper sauce", "potato mash"],
            "ingredient_portions": [
                {"name": "beef steak", "amount": 120, "unit": "g"},
                {"name": "black pepper sauce", "amount": 60, "unit": "ml"},
                {"name": "potato mash", "amount": 70, "unit": "g"},
            ],
            "supplier_key": "beef",
        },
        {
            "name": "Caesar Salad Cup",
            "category": "Side",
            "portion_amount": 100,
            "portion_unit": "g",
            "ingredients": ["lettuce", "parmesan", "croutons", "caesar dressing"],
            "ingredient_portions": [
                {"name": "lettuce", "amount": 35, "unit": "g"},
                {"name": "parmesan", "amount": 20, "unit": "g"},
                {"name": "croutons", "amount": 30, "unit": "g"},
                {"name": "caesar dressing", "amount": 15, "unit": "ml"},
            ],
            "supplier_key": "salad",
        },
        {
            "name": "Roasted Potato Wedges",
            "category": "Side",
            "portion_amount": 120,
            "portion_unit": "g",
            "ingredients": ["potato", "olive oil", "paprika"],
            "ingredient_portions": [
                {"name": "potato", "amount": 80, "unit": "g"},
                {"name": "olive oil", "amount": 10, "unit": "ml"},
                {"name": "paprika", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "potato wedges",
        },
        {
            "name": "Chocolate Brownie Slice",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["dark chocolate", "flour", "cocoa powder"],
            "ingredient_portions": [
                {"name": "dark chocolate", "amount": 20, "unit": "g"},
                {"name": "flour", "amount": 40, "unit": "ml"},
                {"name": "cocoa powder", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "dessert",
        },
    ],

    "none": [
        {
            "name": "Herb Grilled Chicken with Rice",
            "category": "Main",
            "portion_amount": 270,
            "portion_unit": "g",
            "ingredients": ["chicken breast", "rice", "olive oil", "mixed herbs"],
            "ingredient_portions": [
                {"name": "chicken breast", "amount": 100, "unit": "g"},
                {"name": "rice", "amount": 90, "unit": "g"},
                {"name": "olive oil", "amount": 20, "unit": "ml"},
                {"name": "mixed herbs", "amount": 60, "unit": "g"},
            ],
            "supplier_key": "chicken",
        },
        {
            "name": "Beef Steak with Pepper Sauce",
            "category": "Main",
            "portion_amount": 250,
            "portion_unit": "g",
            "ingredients": ["beef steak", "black pepper sauce", "potato mash"],
            "ingredient_portions": [
                {"name": "beef steak", "amount": 120, "unit": "g"},
                {"name": "black pepper sauce", "amount": 60, "unit": "ml"},
                {"name": "potato mash", "amount": 70, "unit": "g"},
            ],
            "supplier_key": "beef",
        },
        {
            "name": "Smoked Salmon Croissant",
            "category": "Side",
            "portion_amount": 120,
            "portion_unit": "g",
            "ingredients": ["croissant", "smoked salmon", "cream cheese"],
            "ingredient_portions": [
                {"name": "croissant", "amount": 30, "unit": "g"},
                {"name": "smoked salmon", "amount": 80, "unit": "g"},
                {"name": "cream cheese", "amount": 10, "unit": "g"},
            ],
            "supplier_key": "salmon",
        },
        {
            "name": "Caesar Salad Cup",
            "category": "Side",
            "portion_amount": 100,
            "portion_unit": "g",
            "ingredients": ["lettuce", "parmesan", "croutons", "caesar dressing"],
            "ingredient_portions": [
                {"name": "lettuce", "amount": 35, "unit": "g"},
                {"name": "parmesan", "amount": 20, "unit": "g"},
                {"name": "croutons", "amount": 30, "unit": "g"},
                {"name": "caesar dressing", "amount": 15, "unit": "ml"},
            ],
            "supplier_key": "salad",
        },
        {
            "name": "Chocolate Brownie Slice",
            "category": "Dessert",
            "portion_amount": 90,
            "portion_unit": "g",
            "ingredients": ["dark chocolate", "flour", "cocoa powder"],
            "ingredient_portions": [
                {"name": "dark chocolate", "amount": 20, "unit": "g"},
                {"name": "flour", "amount": 40, "unit": "ml"},
                {"name": "cocoa powder", "amount": 30, "unit": "g"},
            ],
            "supplier_key": "dessert",
        },
    ],
}