SUPPLIER_AVAILABILITY = {
    "mushroom": ("AVAILABLE", "Cameron Highlands Organic Cooperative", "48 hours"),
    "vegetable": ("AVAILABLE", "Cameron Highlands Organic Cooperative", "48 hours"),
    "tofu": ("AVAILABLE", "Cameron Highlands Organic Cooperative", "48 hours"),
    "rice": ("AVAILABLE", "Local Grain Supplier", "48 hours"),
    "sushi": ("AVAILABLE", "Local Japanese Ingredients Supplier", "48 hours"),
    "seaweed": ("AVAILABLE", "Local Japanese Ingredients Supplier", "48 hours"),
    "wakame": ("AVAILABLE", "Local Japanese Ingredients Supplier", "48 hours"),
    "edamame": ("AVAILABLE", "Frozen Produce Supplier", "48 hours"),
    "avocado": ("LIMITED", "Fresh Produce Supplier", "72 hours"),
    "cucumber": ("AVAILABLE", "Cameron Highlands Organic Cooperative", "48 hours"),
    "sauce": ("AVAILABLE", "Kitchen Prepared", "24 hours"),
    "soup": ("AVAILABLE", "Kitchen Prepared", "24 hours"),
    "prawn": ("CRITICAL SHORTAGE", "Port Klang Daily Catch", "12 hours"),
    "crab": ("CRITICAL SHORTAGE", "Port Klang Daily Catch", "12 hours"),
    "matcha": ("AVAILABLE", "Kyoto Matcha Import Supplier", "72 hours"),
    "chicken": ("AVAILABLE", "KL Central Poultry Farm", "24 hours"),
    "beef": ("LIMITED", "Premium Halal Meat Supplier", "48 hours"),
    "fish": ("AVAILABLE", "Port Klang Daily Catch", "12 hours"),
    "salmon": ("AVAILABLE", "Port Klang Daily Catch", "12 hours"),
    "coconut milk": ("AVAILABLE", "Dessert Prep Kitchen", "48 hours"),
    "gluten-free tamari": ("AVAILABLE", "Japanese Ingredients Supplier", "48 hours"),
    "sushi rice": ("AVAILABLE", "Japanese Ingredients Supplier", "48 hours"),
    "tamari": ("AVAILABLE", "Japanese Sauce Supplier", "48 hours"),
    "teriyaki sauce": ("AVAILABLE", "Japanese Sauce Supplier", "48 hours"),
    "vegan teriyaki sauce": ("LIMITED", "Japanese Sauce Supplier", "48 hours"),
    "carrot": ("AVAILABLE", "Cameron Highlands Organic Cooperative", "48 hours"),
    "nori": ("AVAILABLE", "Japanese Ingredients Supplier", "48 hours"),
    "red bean paste": ("AVAILABLE", "Japanese Dessert Supplier", "48 hours"),
    "mochi": ("LIMITED", "Japanese Dessert Supplier", "72 hours"),
    "gluten-free teriyaki sauce": ("AVAILABLE", "Japanese Ingredients Supplier", "48 hours"),
    "salad": ("AVAILABLE", "Cameron Highlands Organic Cooperative", "48 hours"),
    "mushroom pasta": ("AVAILABLE", "Western Ingredients Supplier", "48 hours"),
    "vegetarian quiche": ("LIMITED", "Bakery Supplier", "72 hours"),
    "fruit cup": ("AVAILABLE", "Fresh Fruit Supplier", "48 hours"),
    "potato wedges": ("AVAILABLE", "Local Produce Supplier", "48 hours"),
    "vegetable curry": ("AVAILABLE", "Malay Ingredients Supplier", "48 hours"),
    "curry puff": ("AVAILABLE", "Malay Snack Supplier", "48 hours"),
    "pickled vegetables": ("AVAILABLE", "Local Produce Supplier", "24 hours"),
    "bok choy": ("AVAILABLE", "Cameron Highlands Organic Cooperative", "48 hours"),
    "gluten-free soy sauce": ("AVAILABLE", "Specialty Sauce Supplier", "72 hours"),
    "gluten-free chili sauce": ("LIMITED", "Specialty Sauce Supplier", "72 hours"),
    "wine": ("AVAILABLE", "KL Premium Spirits & Wines", "48 hours"),
    "beer": ("AVAILABLE", "KL Premium Spirits & Wines", "48 hours"),
    "sake": ("AVAILABLE", "KL Premium Spirits & Wines", "48 hours"),
    "eco-packaging": ("AVAILABLE", "Sustainable MY Solutions", "72 hours"),
    "sea salt": ("AVAILABLE", "Kitchen Pantry Supplier", "24 hours"),
    "vegan mochi": ("LIMITED", "Japanese Dessert Supplier", "72 hours"),
    "seasonal vegetables": ("AVAILABLE", "Cameron Highlands Organic Cooperative", "48 hours"),
    "ginger vegetable broth": ("AVAILABLE", "Kitchen Prepared", "24 hours"),
    "rice flour": ("AVAILABLE", "Local Grain Supplier", "48 hours"),
    "soy sauce": ("AVAILABLE", "Chinese Sauce Supplier", "48 hours"),
    "chili bean sauce": ("AVAILABLE", "Chinese Sauce Supplier", "48 hours"),
    "spring onion": ("AVAILABLE", "Local Produce Supplier", "24 hours"),
    "rice wrapper": ("AVAILABLE", "Chinese Ingredients Supplier", "48 hours"),
    "garlic": ("AVAILABLE", "Local Produce Supplier", "24 hours"),
    "sesame oil": ("AVAILABLE", "Chinese Ingredients Supplier", "48 hours"),
    "mango": ("AVAILABLE", "Fresh Fruit Supplier", "48 hours"),
    "sago": ("AVAILABLE", "Dessert Ingredients Supplier", "48 hours"),
    "egg": ("AVAILABLE", "KL Central Poultry Farm", "24 hours"),
    "glutinous rice": ("AVAILABLE", "Local Grain Supplier", "48 hours"),
    "sesame": ("AVAILABLE", "Chinese Ingredients Supplier", "48 hours"),
    "pineapple": ("CRITICAL SHORTAGE", "Fresh Fruit Supplier", "48 hours"),
    "capsicum": ("AVAILABLE", "Local Produce Supplier", "48 hours"),
    "sweet and sour sauce": ("AVAILABLE", "Chinese Sauce Supplier", "48 hours"),
    "coconut rice": ("AVAILABLE", "Malay Ingredients Supplier", "48 hours"),
    "mushroom sambal": ("AVAILABLE", "Malay Sauce Supplier", "48 hours"),
    "fried tempeh": ("LIMITED", "Local Soy Supplier", "48 hours"),
    "cabbage": ("AVAILABLE", "Cameron Highlands Organic Cooperative", "48 hours"),
    "long beans": ("AVAILABLE", "Local Produce Supplier", "48 hours"),
    "potato": ("AVAILABLE", "Local Produce Supplier", "48 hours"),
    "curry spices": ("AVAILABLE", "Malay Spice Supplier", "48 hours"),
    "pastry": ("AVAILABLE", "Bakery Supplier", "48 hours"),
    "vinegar": ("AVAILABLE", "Kitchen Pantry Supplier", "24 hours"),
    "pandan": ("AVAILABLE", "Malay Dessert Supplier", "48 hours"),
    "sambal": ("AVAILABLE", "Malay Sauce Supplier", "48 hours"),
    "chicken sambal": ("AVAILABLE", "Malay Sauce Supplier", "48 hours"),
    "turmeric": ("AVAILABLE", "Malay Spice Supplier", "48 hours"),
    "lime": ("AVAILABLE", "Fresh Produce Supplier", "24 hours"),
    "chili": ("AVAILABLE", "Fresh Produce Supplier", "24 hours"),
    "cassava": ("CRITICAL SHORTAGE", "Local Produce Supplier", "48 hours"),
    "rendang spices": ("AVAILABLE", "Malay Spice Supplier", "48 hours"),
    "banana leaf": ("CRITICAL SHORTAGE", "Fresh Produce Supplier", "24 hours"),
    "pandan crepe": ("LIMITED", "Malay Dessert Supplier", "48 hours"),
    "grated coconut": ("AVAILABLE", "Dessert Ingredients Supplier", "48 hours"),
    "palm sugar": ("AVAILABLE", "Dessert Ingredients Supplier", "48 hours"),
    "satay spices": ("AVAILABLE", "Malay Spice Supplier", "48 hours"),
    "sugar": ("AVAILABLE", "Kitchen Pantry Supplier", "24 hours"),
    "penne pasta": ("AVAILABLE", "Western Ingredients Supplier", "48 hours"),
    "zucchini": ("AVAILABLE", "Fresh Produce Supplier", "48 hours"),
    "olive oil": ("AVAILABLE", "Kitchen Pantry Supplier", "24 hours"),
    "pumpkin": ("AVAILABLE", "Fresh Produce Supplier", "48 hours"),
    "broccoli": ("AVAILABLE", "Fresh Produce Supplier", "48 hours"),
    "quinoa": ("LIMITED", "Health Grain Supplier", "72 hours"),
    "mixed herbs": ("AVAILABLE", "Kitchen Pantry Supplier", "24 hours"),
    "tomato": ("AVAILABLE", "Fresh Produce Supplier", "24 hours"),
    "basil": ("AVAILABLE", "Fresh Herb Supplier", "24 hours"),
    "bread": ("AVAILABLE", "Bakery Supplier", "24 hours"),
    "lettuce": ("AVAILABLE", "Fresh Produce Supplier", "24 hours"),
    "cherry tomato": ("AVAILABLE", "Fresh Produce Supplier", "24 hours"),
    "vinaigrette": ("AVAILABLE", "Kitchen Pantry Supplier", "24 hours"),
    "chia seeds": ("AVAILABLE", "Health Ingredients Supplier", "72 hours"),
    "mixed berries": ("AVAILABLE", "Frozen Fruit Supplier", "48 hours"),
    "cream sauce": ("AVAILABLE", "Dairy Supplier", "48 hours"),
    "parmesan": ("AVAILABLE", "Dairy Supplier", "48 hours"),
    "spinach": ("AVAILABLE", "Fresh Produce Supplier", "24 hours"),
    "cheese": ("AVAILABLE", "Dairy Supplier", "48 hours"),
    "pastry crust": ("LIMITED", "Bakery Supplier", "48 hours"),
    "cream cheese": ("AVAILABLE", "Dairy Supplier", "48 hours"),
    "biscuit base": ("AVAILABLE", "Bakery Supplier", "48 hours"),
    "berry topping": ("AVAILABLE", "Dessert Supplier", "48 hours"),
    "chicken breast": ("AVAILABLE", "KL Central Poultry Farm", "24 hours"),
    "asparagus": ("LIMITED", "Fresh Produce Supplier", "48 hours"),
    "herb seasoning": ("AVAILABLE", "Kitchen Pantry Supplier", "24 hours"),
    "gluten-free croutons": ("AVAILABLE", "Specialty Bakery Supplier", "72 hours"),
    "caesar dressing": ("AVAILABLE", "Kitchen Pantry Supplier", "24 hours"),
    "melon": ("AVAILABLE", "Fresh Fruit Supplier", "24 hours"),
    "grapes": ("AVAILABLE", "Fresh Fruit Supplier", "24 hours"),
    "strawberries": ("AVAILABLE", "Fresh Fruit Supplier", "24 hours"),
    "dark chocolate": ("AVAILABLE", "Dessert Supplier", "48 hours"),
    "cream": ("AVAILABLE", "Dairy Supplier", "48 hours"),
    "cocoa powder": ("AVAILABLE", "Dessert Supplier", "48 hours"),
    "fish fillet": ("AVAILABLE", "Port Klang Daily Catch", "12 hours"),
    "lemon": ("AVAILABLE", "Fresh Produce Supplier", "24 hours"),
    "paprika": ("AVAILABLE", "Spice Supplier", "48 hours"),
    "berries": ("AVAILABLE", "Frozen Fruit Supplier", "48 hours"),
    "beef steak": ("LIMITED", "Premium Halal Meat Supplier", "48 hours"),
    "black pepper sauce": ("AVAILABLE", "Western Sauce Supplier", "48 hours"),
    "potato mash": ("AVAILABLE", "Kitchen Prepared", "24 hours"),
    "croutons": ("AVAILABLE", "Bakery Supplier", "24 hours"),
    "flour": ("AVAILABLE", "Local Grain Supplier", "48 hours"),
    "croissant": ("AVAILABLE", "Bakery Supplier", "24 hours"),
    "smoked salmon": ("LIMITED", "Seafood Supplier", "48 hours"),
}

def get_supplier_status(item_name: str):
    text = item_name.lower()

    for keyword, data in SUPPLIER_AVAILABILITY.items():
        if keyword in text:
            return data

    return ("UNKNOWN", "No mapped supplier", "Unknown")
